# Generated by Django 4.0.3 on 2022-04-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('due_on', models.DateTimeField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=250, null=True)),
                ('mark', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
